# Generated by Django 2.1.4 on 2019-01-12 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100000)])),
                ('platform_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('expected_arrival', models.CharField(max_length=4)),
                ('content', models.TextField(blank=True, default='No Delay', null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
